steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/christian:${COMMIT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/christian:${COMMIT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'christian'
    - '--image'
    - 'gcr.io/$PROJECT_ID/christian:${COMMIT_SHA}'
    - '--region'
    - 'asia-northeast1' 
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'


images:
  - 'gcr.io/$PROJECT_ID/christian:${COMMIT_SHA}'

substitutions:
  COMMIT_SHA: 'latest'


options:
  logging: CLOUD_LOGGING_ONLY